# Generated by Django 2.1.1 on 2019-01-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190120_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_info',
        ),
    ]
